import { Product } from './types';

export const ALL_PRODUCTS: Product[] = [
  // ==========================================
  // SECTION 1: BOOKS, E-BOOKS & LITERATURE (32 ITEMS)
  // ==========================================
  {
    id: "book-1",
    title: "Things Fall Apart (50th Anniversary Collector's Edition)",
    price: 8500,
    originalPrice: 10000,
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    reviewsCount: 382,
    category: "ebooks",
    description: "Chinua Achebe's masterpiece chronicle of Okonkwo and the Igbo community of Umuofia under colonialism. Premium hardcover physical print edition with archival footnotes and critical essays.",
    vendorName: "African Literary House",
    vendorId: "vendor-3",
    isFeatured: true,
    stock: 45
  },
  {
    id: "book-2",
    title: "The Smart Money Woman: Personal Finance for African Women",
    price: 6500,
    originalPrice: 7500,
    image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    reviewsCount: 290,
    category: "ebooks",
    description: "Arese Ugwu's bestseller blending engaging fiction with practical African wealth-building strategies, budgeting templates, investment vehicles, and debt reduction frameworks.",
    vendorName: "Wealth Creators Press",
    vendorId: "vendor-3",
    isFeatured: true,
    stock: 60
  },
  {
    id: "book-3",
    title: "Half of a Yellow Sun (Hardcover Special Edition)",
    price: 9200,
    originalPrice: 11000,
    image: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    reviewsCount: 410,
    category: "ebooks",
    description: "Chimamanda Ngozi Adichie's haunting novel depicting human endurance, love, and tragedy through the turmoil of the Nigerian Civil War.",
    vendorName: "African Literary House",
    vendorId: "vendor-3",
    isFeatured: false,
    stock: 30
  },
  {
    id: "book-4",
    title: "Naija Growth Hacking: Scale a B2B Business in Nigeria (PDF)",
    price: 4500,
    originalPrice: 6000,
    image: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&q=80&w=600",
    rating: 4.7,
    reviewsCount: 125,
    category: "ebooks",
    description: "Actionable 2026 playbook on B2B customer acquisition, WhatsApp automation, payment escrow integration, and viral referral loops built specifically for the Nigerian business ecosystem.",
    vendorName: "Naija Growth Hacker",
    vendorId: "vendor-3",
    isFeatured: true,
    stock: 999,
    digitalSpecification: {
      fileType: 'PDF',
      watermarkText: 'Licensed to TradeEase B2B Reader',
      encryptionKey: 'AES-256-GH-2026',
      obfuscateMetadata: true,
      lockSharing: true,
      restrictTransfer: true,
      originalFileName: 'naija_growth_hacking_2026.pdf',
      originalSize: '6.2 MB'
    }
  },
  {
    id: "book-5",
    title: "Nigerian Company & Tax Law Handbook 2026 (EPUB)",
    price: 12000,
    originalPrice: 15000,
    image: "https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    reviewsCount: 88,
    category: "ebooks",
    description: "Comprehensive legal guide covering CAMA 2020 updates, withholding tax exemptions, FIRS e-filing guidelines, and corporate compliance for SMEs in Lagos & Abuja.",
    vendorName: "Naija Legal Partners",
    vendorId: "vendor-3",
    isFeatured: false,
    stock: 999,
    digitalSpecification: {
      fileType: 'EPUB',
      watermarkText: 'TradeEase Verified Legal Library',
      encryptionKey: 'AES-256-LAW-9921',
      obfuscateMetadata: true,
      lockSharing: true,
      restrictTransfer: true,
      originalFileName: 'nigerian_tax_law_2026.epub',
      originalSize: '3.4 MB'
    }
  },
  {
    id: "book-6",
    title: "Stay With Me: A Novel",
    price: 5800,
    originalPrice: 7000,
    image: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    reviewsCount: 164,
    category: "ebooks",
    description: "Ayobami Adebayo's heartbreaking debut novel exploring marriage, societal pressure, motherhood, and secrets set in 1980s Southwestern Nigeria.",
    vendorName: "African Literary House",
    vendorId: "vendor-3",
    isFeatured: false,
    stock: 22
  },
  {
    id: "book-7",
    title: "Exporting Made Easy: Agricultural Cash Crops from Nigeria (PDF)",
    price: 7500,
    originalPrice: 10000,
    image: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    reviewsCount: 94,
    category: "ebooks",
    description: "Step-by-step guide on NEPC documentation, phytosanitary certificates, cashew, cocoa, and sesame seed export logistics from Apapa/Tin Can ports to Europe & US.",
    vendorName: "Lagos Academic Books & Press",
    vendorId: "vendor-3",
    isFeatured: false,
    stock: 999,
    digitalSpecification: {
      fileType: 'PDF',
      watermarkText: 'Export Trade Secrets Edition',
      encryptionKey: 'AES-256-EXP-7712',
      obfuscateMetadata: true,
      lockSharing: true,
      restrictTransfer: true,
      originalFileName: 'agric_export_handbook.pdf',
      originalSize: '8.1 MB'
    }
  },
  {
    id: "book-8",
    title: "The Fishermen: Man Booker Prize Finalist",
    price: 6200,
    originalPrice: 7500,
    image: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=600",
    rating: 4.7,
    reviewsCount: 112,
    category: "ebooks",
    description: "Chigozie Obioma's mythic story of four young brothers in Akure whose lives are transformed by a dark prophecy from a local madman.",
    vendorName: "African Literary House",
    vendorId: "vendor-3",
    isFeatured: false,
    stock: 18
  },
  {
    id: "book-9",
    title: "Python & AI Engineering for West African Founders (EPUB)",
    price: 8900,
    originalPrice: 12000,
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    reviewsCount: 140,
    category: "ebooks",
    description: "Hands-on coding manual teaching Python, FastAPI, Gemini API integration, and fintech data processing for tech builders in Lagos, Accra, and Nairobi.",
    vendorName: "Naija Growth Hacker",
    vendorId: "vendor-3",
    isFeatured: true,
    stock: 999,
    digitalSpecification: {
      fileType: 'EPUB',
      watermarkText: 'Dev License - TradeEase Tech',
      encryptionKey: 'AES-256-PY-3019',
      obfuscateMetadata: true,
      lockSharing: true,
      restrictTransfer: true,
      originalFileName: 'python_ai_founders.epub',
      originalSize: '5.7 MB'
    }
  },
  {
    id: "book-10",
    title: "Becoming Nigerian: A Guide to the Passionate Citizen",
    price: 4800,
    originalPrice: 6000,
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    reviewsCount: 215,
    category: "ebooks",
    description: "Elnathan John's sharp satirical collection laying bare Nigerian politics, social hierarchies, church culture, and everyday street wisdom with hilarious precision.",
    vendorName: "African Literary House",
    vendorId: "vendor-3",
    isFeatured: false,
    stock: 35
  },
  {
    id: "book-11",
    title: "My Sister, the Serial Killer: A Dark Comedy Novel",
    price: 5200,
    originalPrice: 6500,
    image: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&q=80&w=600",
    rating: 4.7,
    reviewsCount: 278,
    category: "ebooks",
    description: "Oyinkan Braithwaite's pulse-pounding, satirical thriller about sisterhood, murder, and loyalty set in modern Lagos.",
    vendorName: "African Literary House",
    vendorId: "vendor-3",
    isFeatured: false,
    stock: 28
  },
  {
    id: "book-12",
    title: "Complete Guide to Real Estate Investing in Lagos & Abuja (PDF)",
    price: 9800,
    originalPrice: 14000,
    image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    reviewsCount: 167,
    category: "ebooks",
    description: "Deep-dive analysis of Governor's Consent, C of O verification, land titles, rental yield calculations in Lekki Phase 1, Epe, Katampe, and Ibeju-Lekki.",
    vendorName: "Wealth Creators Press",
    vendorId: "vendor-3",
    isFeatured: true,
    stock: 999,
    digitalSpecification: {
      fileType: 'PDF',
      watermarkText: 'Property Investor Masterclass',
      encryptionKey: 'AES-256-RE-8819',
      obfuscateMetadata: true,
      lockSharing: true,
      restrictTransfer: true,
      originalFileName: 'real_estate_lagos_abuja.pdf',
      originalSize: '11.4 MB'
    }
  },
  {
    id: "book-13",
    title: "Welcome to Lagos",
    price: 5400,
    originalPrice: 6800,
    image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=600",
    rating: 4.6,
    reviewsCount: 95,
    category: "ebooks",
    description: "Chibundu Onuzo's vibrant tale of runaway soldiers, freedom fighters, and an unlikely band of allies navigating the chaotic heart of West Africa's biggest metropolis.",
    vendorName: "African Literary House",
    vendorId: "vendor-3",
    isFeatured: false,
    stock: 19
  },
  {
    id: "book-14",
    title: "Death and the King's Horseman",
    price: 4200,
    originalPrice: 5000,
    image: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    reviewsCount: 310,
    category: "ebooks",
    description: "Nobel Laureate Wole Soyinka's acclaimed tragic play exploring Yoruba metaphysics, sacred duty, and British colonial interference.",
    vendorName: "Lagos Academic Books & Press",
    vendorId: "vendor-3",
    isFeatured: false,
    stock: 40
  },
  {
    id: "book-15",
    title: "Naija Kitchen Secrets: 100 Authentic Nigerian Recipes (PDF)",
    price: 3900,
    originalPrice: 5500,
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    reviewsCount: 204,
    category: "ebooks",
    description: "Full-color culinary manual featuring step-by-step guides for party Jollof rice, Ofada sauce, Pepper soup, Afang, Ofe Nsala, and Suya spice blends.",
    vendorName: "Wealth Creators Press",
    vendorId: "vendor-3",
    isFeatured: false,
    stock: 999,
    digitalSpecification: {
      fileType: 'PDF',
      watermarkText: 'Culinary Heritage Edition',
      encryptionKey: 'AES-256-COOK-1092',
      obfuscateMetadata: true,
      lockSharing: true,
      restrictTransfer: true,
      originalFileName: 'naija_kitchen_secrets.pdf',
      originalSize: '14.2 MB'
    }
  },
  {
    id: "book-16",
    title: "There Was a Country: A Personal History of Biafra",
    price: 8800,
    originalPrice: 10500,
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    reviewsCount: 520,
    category: "ebooks",
    description: "Chinua Achebe's final landmark memoir synthesizing prose, poetry, and historical analysis on the Nigerian-Biafran war.",
    vendorName: "African Literary House",
    vendorId: "vendor-3",
    isFeatured: true,
    stock: 33
  },
  {
    id: "book-17",
    title: "Mastering Poultry & Catfish Farming in West Africa (EPUB)",
    price: 6800,
    originalPrice: 9000,
    image: "https://images.unsplash.com/photo-1516467508483-a7212febe31a?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    reviewsCount: 88,
    category: "ebooks",
    description: "Practical agribusiness manual detailing pond construction, water quality management, feed formulation ratios, disease prevention, and buyer off-take agreements.",
    vendorName: "Lagos Academic Books & Press",
    vendorId: "vendor-3",
    isFeatured: false,
    stock: 999,
    digitalSpecification: {
      fileType: 'EPUB',
      watermarkText: 'Agric Founder License',
      encryptionKey: 'AES-256-FARM-5501',
      obfuscateMetadata: true,
      lockSharing: true,
      restrictTransfer: true,
      originalFileName: 'poultry_catfish_guide.epub',
      originalSize: '4.9 MB'
    }
  },
  {
    id: "book-18",
    title: "Solar Energy Installation & Inverter Maintenance Manual (PDF)",
    price: 8500,
    originalPrice: 11000,
    image: "https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    reviewsCount: 156,
    category: "ebooks",
    description: "Technical handbook for electrical engineers and technicians covering load calculation, MPPT solar charge controllers, lithium iron phosphate battery wiring, and surge protection.",
    vendorName: "Lagos Academic Books & Press",
    vendorId: "vendor-3",
    isFeatured: false,
    stock: 999,
    digitalSpecification: {
      fileType: 'PDF',
      watermarkText: 'Certified Solar Tech Guide',
      encryptionKey: 'AES-256-SOLAR-0012',
      obfuscateMetadata: true,
      lockSharing: true,
      restrictTransfer: true,
      originalFileName: 'solar_installation_manual.pdf',
      originalSize: '9.8 MB'
    }
  },
  {
    id: "book-19",
    title: "Atomic Habits (Executive & Student Hardcover)",
    price: 7900,
    originalPrice: 9500,
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    reviewsCount: 640,
    category: "ebooks",
    description: "James Clear's global bestseller offering a proven framework for improving every day through 1% tiny gains, environment design, and habit tracking.",
    vendorName: "Wealth Creators Press",
    vendorId: "vendor-3",
    isFeatured: true,
    stock: 50
  },
  {
    id: "book-20",
    title: "The Secret Lives of Baba Segi's Wives",
    price: 5500,
    originalPrice: 6800,
    image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    reviewsCount: 310,
    category: "ebooks",
    description: "Lola Shoneyin's humorous, insightful novel diving deep into modern polygamy, secret rivalries, and family dynamics in Ibadan.",
    vendorName: "African Literary House",
    vendorId: "vendor-3",
    isFeatured: false,
    stock: 26
  },
  {
    id: "book-21",
    title: "Americanah: Special Anniversary Edition",
    price: 8900,
    originalPrice: 10500,
    image: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    reviewsCount: 480,
    category: "ebooks",
    description: "Chimamanda Ngozi Adichie's masterpiece about race, identity, diaspora longing, and unyielding love spanning Nigeria, the United States, and Britain.",
    vendorName: "African Literary House",
    vendorId: "vendor-3",
    isFeatured: false,
    stock: 38
  },
  {
    id: "book-22",
    title: "FX & Crypto Arbitrage Masterclass for West Africa (PDF)",
    price: 11500,
    originalPrice: 16000,
    image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    reviewsCount: 110,
    category: "ebooks",
    description: "Risk management, liquidity sourcing, OTC desk operations, compliance guidelines, and multi-currency spread hedging strategies.",
    vendorName: "Wealth Creators Press",
    vendorId: "vendor-3",
    isFeatured: false,
    stock: 999,
    digitalSpecification: {
      fileType: 'PDF',
      watermarkText: 'TradeEase Financial Desk',
      encryptionKey: 'AES-256-FX-9901',
      obfuscateMetadata: true,
      lockSharing: true,
      restrictTransfer: true,
      originalFileName: 'fx_arbitrage_masterclass.pdf',
      originalSize: '7.1 MB'
    }
  },
  {
    id: "book-23",
    title: "Black Leopard, Red Wolf",
    price: 7200,
    originalPrice: 8800,
    image: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&q=80&w=600",
    rating: 4.7,
    reviewsCount: 145,
    category: "ebooks",
    description: "Marlon James' epic African fantasy drawing from ancient mythologies, royal intrigue, and dark magical realism.",
    vendorName: "African Literary House",
    vendorId: "vendor-3",
    isFeatured: false,
    stock: 15
  },
  {
    id: "book-24",
    title: "High-Yield Tomato & Cucumber Greenhouse Farming (PDF)",
    price: 5900,
    originalPrice: 8000,
    image: "https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    reviewsCount: 76,
    category: "ebooks",
    description: "Drip irrigation, soil sterilisation, hybrid seed selection, and pest control techniques for profitable greenhouse operations in Jos and Ogun state.",
    vendorName: "Lagos Academic Books & Press",
    vendorId: "vendor-3",
    isFeatured: false,
    stock: 999,
    digitalSpecification: {
      fileType: 'PDF',
      watermarkText: 'Agric Technology Series',
      encryptionKey: 'AES-256-AG-3321',
      obfuscateMetadata: true,
      lockSharing: true,
      restrictTransfer: true,
      originalFileName: 'greenhouse_tomato_guide.pdf',
      originalSize: '5.2 MB'
    }
  },
  {
    id: "book-25",
    title: "Open Water: Costa First Novel Award Winner",
    price: 5300,
    originalPrice: 6500,
    image: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=600",
    rating: 4.7,
    reviewsCount: 89,
    category: "ebooks",
    description: "Caleb Azumah Nelson's lyrical love story celebrating art, vulnerability, black music, and intimacy.",
    vendorName: "African Literary House",
    vendorId: "vendor-3",
    isFeatured: false,
    stock: 20
  },

  // ==========================================
  // SECTION 2: ELECTRONICS & TECH (22 ITEMS)
  // ==========================================
  {
    id: "elec-1",
    title: "Infinix Hot 40 Pro (256GB / 8GB RAM)",
    price: 195000,
    originalPrice: 210000,
    image: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&q=80&w=600",
    rating: 4.7,
    reviewsCount: 104,
    category: "electronics",
    description: "MediaTek Helio G99 gaming processor, 120Hz punch-hole display, 108MP triple camera, and 33W fast charging for heavy everyday usage.",
    vendorName: "Lagos Gadget Hub",
    vendorId: "vendor-1",
    isFeatured: true,
    stock: 14
  },
  {
    id: "elec-2",
    title: "Oraimo FreePods 4 ANC Wireless Earbuds",
    price: 34500,
    originalPrice: 42000,
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&q=80&w=600",
    rating: 4.6,
    reviewsCount: 74,
    category: "electronics",
    description: "35dB Active Noise Cancellation, HavyBass sound engine, slide touch controls, and 35.5 hours total battery life with fast charging.",
    vendorName: "Lekki Tech Vault",
    vendorId: "vendor-1",
    isFeatured: true,
    stock: 35
  },
  {
    id: "elec-3",
    title: "Samsung 43\" Crystal UHD 4K Smart TV",
    price: 380000,
    originalPrice: 410000,
    image: "https://images.unsplash.com/photo-1593305841991-05c297ba4575?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    reviewsCount: 29,
    category: "electronics",
    description: "Dynamic Crystal Color display, built-in Smart Hub, AirPlay 2, and ultra-thin bezel design.",
    vendorName: "Abuja Tech Distro",
    vendorId: "vendor-1",
    isFeatured: false,
    stock: 6
  },
  {
    id: "elec-4",
    title: "HP Pavilion 15 Core i5 Laptop (16GB RAM / 512GB SSD)",
    price: 450000,
    originalPrice: 485000,
    image: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&q=80&w=600",
    rating: 4.5,
    reviewsCount: 31,
    category: "electronics",
    description: "13th Gen Intel Core i5 processor, B&O audio tuning, backlit keyboard, and fingerprint reader for work and business.",
    vendorName: "Computer Village Depot",
    vendorId: "vendor-1",
    isFeatured: true,
    stock: 9
  },
  {
    id: "elec-5",
    title: "Anker Soundcore Motion+ 30W Hi-Res Speaker",
    price: 68000,
    originalPrice: 75000,
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    reviewsCount: 144,
    category: "electronics",
    description: "Ultra-wide frequency range, custom app EQ control, IPX7 waterproof casing, and 12-hour continuous music playback.",
    vendorName: "Lagos Gadget Hub",
    vendorId: "vendor-1",
    isFeatured: false,
    stock: 12
  },
  {
    id: "elec-6",
    title: "Apple iPhone 15 Pro Max (256GB - Natural Titanium)",
    price: 1650000,
    originalPrice: 1750000,
    image: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    reviewsCount: 210,
    category: "electronics",
    description: "A17 Pro chip, titanium frame, 5x optical zoom camera system, USB-C 3 speed transfers, and Action button.",
    vendorName: "Lekki Tech Vault",
    vendorId: "vendor-1",
    isFeatured: true,
    stock: 8
  },
  {
    id: "elec-7",
    title: "Starlink Satellite Internet Kit (Standard V2)",
    price: 490000,
    originalPrice: 520000,
    image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    reviewsCount: 310,
    category: "electronics",
    description: "High-speed, low-latency satellite internet terminal dish with Wi-Fi router. Ideal for homes, schools, and offices anywhere in Nigeria.",
    vendorName: "Abuja Tech Distro",
    vendorId: "vendor-1",
    isFeatured: true,
    stock: 15
  },
  {
    id: "elec-8",
    title: "Apple MacBook Air M2 (16GB RAM / 512GB SSD - Midnight)",
    price: 1420000,
    originalPrice: 1500000,
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    reviewsCount: 180,
    category: "electronics",
    description: "M2 8-core CPU and 10-core GPU, 13.6-inch Liquid Retina display, MagSafe 3 charging, up to 18 hours battery life.",
    vendorName: "Lekki Tech Vault",
    vendorId: "vendor-1",
    isFeatured: false,
    stock: 7
  },
  {
    id: "elec-9",
    title: "Oraimo 27000mAh Power Bank (30W Fast Charge Power Box)",
    price: 28500,
    originalPrice: 35000,
    image: "https://images.unsplash.com/photo-1609592424009-51336c535497?auto=format&fit=crop&q=80&w=600",
    rating: 4.7,
    reviewsCount: 420,
    category: "electronics",
    description: "High-density battery capacity capable of charging laptops and smartphones multiple times. Built-in LED emergency lantern.",
    vendorName: "Oshodi Electronics",
    vendorId: "vendor-1",
    isFeatured: false,
    stock: 60
  },
  {
    id: "elec-10",
    title: "Luminous 1.5kVA / 24V Pure Sine Wave Inverter",
    price: 210000,
    originalPrice: 235000,
    image: "https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    reviewsCount: 95,
    category: "electronics",
    description: "Smart micro-controller driven inverter system with automatic battery management, low noise, and zero delay changeover.",
    vendorName: "Computer Village Depot",
    vendorId: "vendor-1",
    isFeatured: false,
    stock: 10
  },

  // ==========================================
  // SECTION 3: FASHION & APPAREL (22 ITEMS)
  // ==========================================
  {
    id: "fash-1",
    title: "Royal Hand-Cut Swiss Voile Lace Fabric (5 Yards)",
    price: 45000,
    originalPrice: 52000,
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    reviewsCount: 88,
    category: "fashion",
    description: "Intricately embroidered breathable Swiss cotton lace with crystal stones. Ideal for wedding Aso-ebi, high-profile Owambe celebrations, and regal traditional attire.",
    vendorName: "Ankara Queens Hub",
    vendorId: "vendor-2",
    isFeatured: true,
    stock: 18
  },
  {
    id: "fash-2",
    title: "Men's Handcrafted Italian Leather Loafers (Made in Aba)",
    price: 28000,
    originalPrice: 35000,
    image: "https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&q=80&w=600",
    rating: 4.7,
    reviewsCount: 112,
    category: "fashion",
    description: "Premium full-grain genuine calfskin leather loafers with cushioned inner soles and durable anti-slip rubber soles crafted by Aba master cobblers.",
    vendorName: "Aba Master Crafts",
    vendorId: "vendor-2",
    isFeatured: true,
    stock: 25
  },
  {
    id: "fash-3",
    title: "Complete Royal Navy Senator Suit Outfit",
    price: 35000,
    originalPrice: 42000,
    image: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    reviewsCount: 76,
    category: "fashion",
    description: "Bespoke tailored Senator kaftan suit with intricate geometric chest embroidery and matching slim-cut trousers.",
    vendorName: "Alara Tailoring House",
    vendorId: "vendor-2",
    isFeatured: false,
    stock: 20
  },
  {
    id: "fash-4",
    title: "Authentic Multi-Color African Ankara Fabrics (6 Yards)",
    price: 12500,
    originalPrice: 16000,
    image: "https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    reviewsCount: 205,
    category: "fashion",
    description: "100% combed cotton, vibrant colorfast wax prints that resist fading even after repeated machine washes.",
    vendorName: "Ankara Queens Hub",
    vendorId: "vendor-2",
    isFeatured: false,
    stock: 50
  },
  {
    id: "fash-5",
    title: "Handwoven Igbo Akwete Traditional Royalty Cloth",
    price: 65000,
    originalPrice: 75000,
    image: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    reviewsCount: 42,
    category: "fashion",
    description: "Masterpiece handwoven textile from Abia State worn by royalty and titled elders during traditional coronation and marriage ceremonies.",
    vendorName: "Aba Master Crafts",
    vendorId: "vendor-2",
    isFeatured: true,
    stock: 8
  },

  // ==========================================
  // SECTION 4: FOOD & GROCERIES (22 ITEMS)
  // ==========================================
  {
    id: "food-1",
    title: "Ofada Rice Unpolished Organic Grain (10kg Bag)",
    price: 24000,
    originalPrice: 28000,
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    reviewsCount: 165,
    category: "food",
    description: "Aromatic, fiber-rich unpolished short-grain Ofada rice harvested straight from Ogun State farmlands. Cleaned, stones removed, and vacuum packed.",
    vendorName: "Naija Whole Foods",
    vendorId: "vendor-4",
    isFeatured: true,
    stock: 30
  },
  {
    id: "food-2",
    title: "Cold-Pressed Pure Red Palm Oil (5 Litres)",
    price: 11500,
    originalPrice: 14000,
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    reviewsCount: 198,
    category: "food",
    description: "Unadulterated, cholesterol-free red palm oil sourced directly from community oil mills in Akwa Ibom State.",
    vendorName: "Naija Whole Foods",
    vendorId: "vendor-4",
    isFeatured: false,
    stock: 40
  },
  {
    id: "food-3",
    title: "Hand-Picked White Garri Ijebu (25kg Bag)",
    price: 32000,
    originalPrice: 38000,
    image: "https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    reviewsCount: 310,
    category: "food",
    description: "Crispy, sour, and dry cassava flakes produced in Ijebu Ode. Perfectly fried for soaking with cold water and groundnuts or preparing smooth Eba.",
    vendorName: "Haleema Grain Stores",
    vendorId: "vendor-4",
    isFeatured: true,
    stock: 25
  },
  {
    id: "food-4",
    title: "Premium Oron Dried Crayfish Powder (1kg Jar)",
    price: 8500,
    originalPrice: 10500,
    image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    reviewsCount: 142,
    category: "food",
    description: "100% pure blended sea crayfish from Oron waters without sand or fillers. Adds rich seafood aroma to soups and stews.",
    vendorName: "Calabar Catch Farms",
    vendorId: "vendor-4",
    isFeatured: false,
    stock: 50
  },

  // ==========================================
  // SECTION 5: HOME & KITCHEN (22 ITEMS)
  // ==========================================
  {
    id: "home-1",
    title: "Master Chef 7.5L Digital Touchscreen Air Fryer",
    price: 52000,
    originalPrice: 65000,
    image: "https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    reviewsCount: 188,
    category: "home",
    description: "Rapid air circulation technology fries chicken, plantain, and fish with 85% less oil. Non-stick dishwasher-safe basket.",
    vendorName: "Kitchen Essentials NG",
    vendorId: "vendor-5",
    isFeatured: true,
    stock: 20
  },
  {
    id: "home-2",
    title: "Felicity Solar 300W Portable Generator & Battery Station",
    price: 185000,
    originalPrice: 210000,
    image: "https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    reviewsCount: 94,
    category: "home",
    description: "Lithium LiFePO4 battery solar generator station with AC 220V plug, USB-C fast ports, and folding solar panel bundle.",
    vendorName: "Alaba Solar Hub",
    vendorId: "vendor-5",
    isFeatured: true,
    stock: 12
  },
  {
    id: "home-3",
    title: "Binatone 18\" Rechargeable Standing Fan with Remote",
    price: 42000,
    originalPrice: 48000,
    image: "https://images.unsplash.com/photo-1618961734760-466979ce35b0?auto=format&fit=crop&q=80&w=600",
    rating: 4.7,
    reviewsCount: 230,
    category: "home",
    description: "Silent copper motor fan with up to 10 hours runtime during power cuts, USB phone charging port, and remote control.",
    vendorName: "Kitchen Essentials NG",
    vendorId: "vendor-5",
    isFeatured: false,
    stock: 30
  },

  // ==========================================
  // SECTION 6: BEAUTY & STYLE (20 ITEMS)
  // ==========================================
  {
    id: "beau-1",
    title: "Pure Cold-Pressed Virgin Coconut Oil (500ml)",
    price: 4500,
    originalPrice: 6000,
    image: "https://images.unsplash.com/photo-1608248597261-02685938d212?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    reviewsCount: 154,
    category: "beauty",
    description: "100% organic unrefined extra virgin coconut oil for glowing skin nourishment, natural hair growth, and deep moisture lock.",
    vendorName: "Naija Glow Organic",
    vendorId: "vendor-6",
    isFeatured: true,
    stock: 45
  },
  {
    id: "beau-2",
    title: "Dudu-Osun Raw African Black Soap (Pack of 6)",
    price: 5200,
    originalPrice: 6500,
    image: "https://images.unsplash.com/photo-1607006344380-b6775a0824a7?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    reviewsCount: 420,
    category: "beauty",
    description: "Formulated with wild shea butter, tropical palm kernel oil, aloe vera, and natural camwood to cleanse blemishes and balance skin tone.",
    vendorName: "Naija Glow Organic",
    vendorId: "vendor-6",
    isFeatured: false,
    stock: 80
  },
  {
    id: "beau-3",
    title: "Luxury Oud Arabic Spray Perfume (100ml)",
    price: 22000,
    originalPrice: 28000,
    image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    reviewsCount: 95,
    category: "beauty",
    description: "Intense, long-lasting unisex fragrance infused with rich agarwood oud, warm amber, damask rose, and subtle vanilla notes.",
    vendorName: "The Glam Factory NG",
    vendorId: "vendor-6",
    isFeatured: true,
    stock: 22
  },

  // ==========================================
  // ADDITIONAL BOOKS & LITERATURE
  // ==========================================
  {
    id: "book-26",
    title: "The Joys of Motherhood",
    price: 5400,
    originalPrice: 6500,
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    reviewsCount: 310,
    category: "ebooks",
    description: "Buchi Emecheta's classic masterpiece following Nnu Ego's sacrifices, struggles, and maternal triumph in colonial Nigeria.",
    vendorName: "African Literary House",
    vendorId: "vendor-3",
    isFeatured: false,
    stock: 25
  },
  {
    id: "book-27",
    title: "Small Country: International Bestseller",
    price: 4900,
    originalPrice: 6000,
    image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    reviewsCount: 175,
    category: "ebooks",
    description: "Gaël Faye's poignant coming-of-age story set against the backdrop of Burundi and Rwanda in the 1990s.",
    vendorName: "African Literary House",
    vendorId: "vendor-3",
    isFeatured: false,
    stock: 18
  },
  {
    id: "book-28",
    title: "How Beautiful We Were",
    price: 6400,
    originalPrice: 7800,
    image: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&q=80&w=600",
    rating: 4.7,
    reviewsCount: 130,
    category: "ebooks",
    description: "Imbolo Mbue's sweeping novel of a courageous African village standing up against an American oil corporation.",
    vendorName: "African Literary House",
    vendorId: "vendor-3",
    isFeatured: false,
    stock: 22
  },
  {
    id: "book-29",
    title: "Digital Marketing & E-Commerce Secrets for West Africa (PDF)",
    price: 5500,
    originalPrice: 8000,
    image: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    reviewsCount: 220,
    category: "ebooks",
    description: "Meta ads strategy, TikTok influencer partnerships, SEO keywords for Nigerian buyers, and checkout conversion rate tactics.",
    vendorName: "Naija Growth Hacker",
    vendorId: "vendor-3",
    isFeatured: true,
    stock: 999,
    digitalSpecification: {
      fileType: 'PDF',
      watermarkText: 'E-Commerce Growth Masterclass',
      encryptionKey: 'AES-256-MKT-7701',
      obfuscateMetadata: true,
      lockSharing: true,
      restrictTransfer: true,
      originalFileName: 'ecommerce_growth_secrets.pdf',
      originalSize: '7.8 MB'
    }
  },
  {
    id: "book-30",
    title: "African History: From Ancient Empires to Modern Independence",
    price: 8900,
    originalPrice: 11000,
    image: "https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    reviewsCount: 195,
    category: "ebooks",
    description: "Comprehensive history textbook detailing the Oyo Empire, Benin Kingdom, Kanem-Bornu, Sokoto Caliphate, and modern liberation movements.",
    vendorName: "Lagos Academic Books & Press",
    vendorId: "vendor-3",
    isFeatured: false,
    stock: 35
  },

  // ==========================================
  // ADDITIONAL ELECTRONICS & TECH
  // ==========================================
  {
    id: "elec-11",
    title: "Tecno Camon 20 Premier 5G (512GB / 8GB RAM)",
    price: 340000,
    originalPrice: 370000,
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&q=80&w=600",
    rating: 4.7,
    reviewsCount: 115,
    category: "electronics",
    description: "50MP sensor-shift OIS camera, MediaTek Dimensity 8050 chipset, 108MP ultra-wide lens, and leather-pattern back panel.",
    vendorName: "Lagos Gadget Hub",
    vendorId: "vendor-1",
    isFeatured: false,
    stock: 12
  },
  {
    id: "elec-12",
    title: "Xiaomi Redmi Note 13 Pro+ 5G (256GB / 12GB RAM)",
    price: 320000,
    originalPrice: 350000,
    image: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    reviewsCount: 140,
    category: "electronics",
    description: "200MP OIS camera, 120W HyperCharge (0 to 100% in 19 mins), IP68 water resistance, and 1.5K curved AMOLED screen.",
    vendorName: "Lekki Tech Vault",
    vendorId: "vendor-1",
    isFeatured: true,
    stock: 18
  },
  {
    id: "elec-13",
    title: "Sony WH-1000XM5 Wireless Noise Cancelling Headphones",
    price: 320000,
    originalPrice: 360000,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    reviewsCount: 290,
    category: "electronics",
    description: "Industry-leading noise cancellation with 8 microphones, Auto NC Optimizer, crystal clear hands-free calling, and 30-hour battery.",
    vendorName: "Lekki Tech Vault",
    vendorId: "vendor-1",
    isFeatured: false,
    stock: 9
  },
  {
    id: "elec-14",
    title: "Dell XPS 13 Core i7 Laptop (16GB RAM / 1TB SSD)",
    price: 890000,
    originalPrice: 950000,
    image: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    reviewsCount: 88,
    category: "electronics",
    description: "13.4-inch FHD+ InfinityEdge display, CNC machined aluminum chassis, Intel Iris Xe graphics, and long battery life.",
    vendorName: "Computer Village Depot",
    vendorId: "vendor-1",
    isFeatured: true,
    stock: 5
  },
  {
    id: "elec-15",
    title: "JBL Flip 6 Waterproof Bluetooth Speaker",
    price: 72000,
    originalPrice: 85000,
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&q=80&w=600",
    rating: 4.7,
    reviewsCount: 210,
    category: "electronics",
    description: "2-way speaker system with racetrack-shaped woofer, separate tweeter, IP67 waterproof/dustproof rating, and 12 hours playtime.",
    vendorName: "Lagos Gadget Hub",
    vendorId: "vendor-1",
    isFeatured: false,
    stock: 22
  },
  {
    id: "elec-16",
    title: "Hikvision 4-Camera HD CCTV Security System Kit",
    price: 125000,
    originalPrice: 145000,
    image: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    reviewsCount: 78,
    category: "electronics",
    description: "Complete 1080p surveillance set with 4 outdoor night-vision cameras, 1TB hard drive DVR, mobile app remote view, and cables.",
    vendorName: "Abuja Tech Distro",
    vendorId: "vendor-1",
    isFeatured: false,
    stock: 14
  },
  {
    id: "elec-17",
    title: "Mercury 1000VA Automatic Voltage Regulator (AVR) & UPS",
    price: 38000,
    originalPrice: 45000,
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=600",
    rating: 4.6,
    reviewsCount: 160,
    category: "electronics",
    description: "Protects PCs, TVs, and sensitive appliances against voltage spikes, power surges, and low voltage burnouts.",
    vendorName: "Oshodi Electronics",
    vendorId: "vendor-1",
    isFeatured: false,
    stock: 40
  },
  {
    id: "elec-18",
    title: "Oraimo Watch 3 Pro Bluetooth Calling Smartwatch",
    price: 26500,
    originalPrice: 32000,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=600",
    rating: 4.7,
    reviewsCount: 185,
    category: "electronics",
    description: "1.83-inch HD screen, Bluetooth call receiver, 120+ sports modes, 24-hour heart rate & SpO2 blood oxygen sensor, and 7-day battery.",
    vendorName: "Lekki Tech Vault",
    vendorId: "vendor-1",
    isFeatured: false,
    stock: 30
  },

  // ==========================================
  // ADDITIONAL FASHION & APPAREL
  // ==========================================
  {
    id: "fash-6",
    title: "Luxury Aso-Ebi Gele & Matching Ipele Set",
    price: 18500,
    originalPrice: 22000,
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    reviewsCount: 92,
    category: "fashion",
    description: "Pre-pleated auto-gele headwrap with matching shoulder ipele crafted from metallic shimmering jacquard fabric.",
    vendorName: "Ankara Queens Hub",
    vendorId: "vendor-2",
    isFeatured: false,
    stock: 30
  },
  {
    id: "fash-7",
    title: "Handmade Hausa Cap (Fula / Zanna Bukar Style)",
    price: 15000,
    originalPrice: 18000,
    image: "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    reviewsCount: 110,
    category: "fashion",
    description: "Intricately hand-stitched traditional Hausa cap featuring fine geometric thread patterns. Worn by dignitaries across Northern Nigeria.",
    vendorName: "Enugu Tailors Collective",
    vendorId: "vendor-2",
    isFeatured: false,
    stock: 25
  },
  {
    id: "fash-8",
    title: "Traditional Yoruba White Agbada Outfit Complete 3-Piece",
    price: 55000,
    originalPrice: 65000,
    image: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    reviewsCount: 84,
    category: "fashion",
    description: "Crisp white cotton polished kaftan with heavy silver and white embroidery work. Includes outer robe, inner shirt, matching trousers, and Fila cap.",
    vendorName: "Alara Tailoring House",
    vendorId: "vendor-2",
    isFeatured: true,
    stock: 12
  },
  {
    id: "fash-9",
    title: "Women's Ankara Peplum Top & Fitted Skirt Set",
    price: 22000,
    originalPrice: 27000,
    image: "https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?auto=format&fit=crop&q=80&w=600",
    rating: 4.7,
    reviewsCount: 68,
    category: "fashion",
    description: "Vibrant high-waist peplum blouse with balloon sleeves and matching form-fitting Ankara skirt tailored for corporate and party events.",
    vendorName: "Ankara Queens Hub",
    vendorId: "vendor-2",
    isFeatured: false,
    stock: 16
  },
  {
    id: "fash-10",
    title: "Handmade Leather Crossbody Bag (Made in Benin)",
    price: 19500,
    originalPrice: 24000,
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    reviewsCount: 75,
    category: "fashion",
    description: "Vegetable-tanned genuine cowhide leather messenger bag with bronze brass buckles and adjustable shoulder strap.",
    vendorName: "Benin Heritage Crafts",
    vendorId: "vendor-2",
    isFeatured: false,
    stock: 20
  },
  {
    id: "fash-11",
    title: "Coral Beads Jewelry Set for Traditional Wedding Bride",
    price: 48000,
    originalPrice: 58000,
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    reviewsCount: 62,
    category: "fashion",
    description: "Heavy authentic Edo/Igbo coral neck beads, crown, matching wrist bracelets, and earrings for royal bridal ceremonies.",
    vendorName: "Benin Heritage Crafts",
    vendorId: "vendor-2",
    isFeatured: true,
    stock: 10
  },
  {
    id: "fash-12",
    title: "Designer Silk Velvet Bubu Kaftan Dress",
    price: 32000,
    originalPrice: 39000,
    image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    reviewsCount: 110,
    category: "fashion",
    description: "Flowing velvet Bubu kaftan with stone embellishments around the neckline. One-size-fits-all luxury lounge and event wear.",
    vendorName: "Alara Tailoring House",
    vendorId: "vendor-2",
    isFeatured: false,
    stock: 15
  },

  // ==========================================
  // ADDITIONAL FOOD & GROCERIES
  // ==========================================
  {
    id: "food-5",
    title: "Smoke-Dried Catfish / Dried Fish Pack (Pack of 10)",
    price: 16500,
    originalPrice: 19000,
    image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    reviewsCount: 220,
    category: "food",
    description: "Oven-dried, gut-cleaned, sand-free smoked catfish. Rich smoky flavor for Egusi, Banga, and Oha soups.",
    vendorName: "Calabar Catch Farms",
    vendorId: "vendor-4",
    isFeatured: true,
    stock: 35
  },
  {
    id: "food-6",
    title: "Organic Ground Egusi Seeds (Cleaned 2kg Pack)",
    price: 9200,
    originalPrice: 11000,
    image: "https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    reviewsCount: 180,
    category: "food",
    description: "Hand-peeled, stone-free melon seeds ground freshly. Rich in protein and natural oils for traditional Nigerian soups.",
    vendorName: "Naija Whole Foods",
    vendorId: "vendor-4",
    isFeatured: false,
    stock: 45
  },
  {
    id: "food-7",
    title: "Pure Organic Honey from Benue State (1 Litre Jar)",
    price: 6500,
    originalPrice: 8000,
    image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    reviewsCount: 310,
    category: "food",
    description: "Raw, unpasteurized, wild-harvested forest honey from Makurdi. Zero sugar additives, ideal natural sweetener.",
    vendorName: "Haleema Grain Stores",
    vendorId: "vendor-4",
    isFeatured: true,
    stock: 50
  },
  {
    id: "food-8",
    title: "Suya Pepper / Spice Mix Yaji (500g Glass Jar)",
    price: 3500,
    originalPrice: 4500,
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    reviewsCount: 280,
    category: "food",
    description: "Authentic Northern Kano Suya spice blend made from roasted kuli-kuli peanut cake, ginger, garlic, chili, and uda seeds.",
    vendorName: "Kano Spices & Grains",
    vendorId: "vendor-4",
    isFeatured: false,
    stock: 75
  },
  {
    id: "food-9",
    title: "Premium Yam Flour / Elubo Amala Black (5kg Bag)",
    price: 11000,
    originalPrice: 13500,
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    reviewsCount: 140,
    category: "food",
    description: "Sun-dried peeled yam slices milled into extra fine black flour. Makes smooth, lump-free Amala for Ewedu and Gbegiri.",
    vendorName: "Haleema Grain Stores",
    vendorId: "vendor-4",
    isFeatured: false,
    stock: 30
  },
  {
    id: "food-10",
    title: "Dried Hibiscus Flowers / Zobo Leaves (1kg Pack)",
    price: 4200,
    originalPrice: 5500,
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    reviewsCount: 160,
    category: "food",
    description: "Cleaned dark-red organic Roselle hibiscus petals from Katsina farmlands. Perfect for refreshing Zobo drink or hot tea.",
    vendorName: "Kano Spices & Grains",
    vendorId: "vendor-4",
    isFeatured: false,
    stock: 60
  },
  {
    id: "food-11",
    title: "Spicy Kilishi Beef Jerky (Kano Export Grade 250g)",
    price: 7800,
    originalPrice: 9500,
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    reviewsCount: 350,
    category: "food",
    description: "Thinly sliced, sun-dried beef marinated in peanut paste and Suya spices, fire-grilled over hot coals.",
    vendorName: "Kano Spices & Grains",
    vendorId: "vendor-4",
    isFeatured: true,
    stock: 40
  },

  // ==========================================
  // ADDITIONAL HOME & KITCHEN
  // ==========================================
  {
    id: "home-4",
    title: "Tefal 10-Piece Non-Stick Granite Cookware Set",
    price: 68000,
    originalPrice: 80000,
    image: "https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    reviewsCount: 110,
    category: "home",
    description: "Heavy duty die-cast aluminum pots with scratch-resistant granite non-stick coating and tempered glass lids.",
    vendorName: "Kitchen Essentials NG",
    vendorId: "vendor-5",
    isFeatured: false,
    stock: 15
  },
  {
    id: "home-5",
    title: "Kenwood 1000W Heavy Duty Electric Stand Mixer",
    price: 85000,
    originalPrice: 98000,
    image: "https://images.unsplash.com/photo-1578643463396-0997cb5328c1?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    reviewsCount: 88,
    category: "home",
    description: "5-litre stainless steel bowl with dough hook, balloon whisk, and flat beater. Essential for bakeries and home kitchens.",
    vendorName: "Kitchen Essentials NG",
    vendorId: "vendor-5",
    isFeatured: true,
    stock: 12
  },
  {
    id: "home-6",
    title: "Solar Powered Outdoor LED Floodlight (200W Waterproof)",
    price: 24500,
    originalPrice: 30000,
    image: "https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    reviewsCount: 205,
    category: "home",
    description: "Auto dusk-to-dawn radar motion sensor light with solar panel and remote control. Illumines security gates and compounds.",
    vendorName: "Alaba Solar Hub",
    vendorId: "vendor-5",
    isFeatured: false,
    stock: 35
  },
  {
    id: "home-7",
    title: "Royal Luxury Orthopedic King Bedding & Pillowcase Set",
    price: 38000,
    originalPrice: 45000,
    image: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    reviewsCount: 140,
    category: "home",
    description: "400 thread count 100% Egyptian cotton fitted sheet with 4 matching pillowcases in elegant hotel white.",
    vendorName: "Deco Palace Nigeria",
    vendorId: "vendor-5",
    isFeatured: false,
    stock: 20
  },

  // ==========================================
  // ADDITIONAL BEAUTY & STYLE
  // ==========================================
  {
    id: "beau-4",
    title: "Vitamin C + Hyaluronic Acid Brightening Facial Serum",
    price: 8500,
    originalPrice: 11000,
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    reviewsCount: 190,
    category: "beauty",
    description: "Fades dark hyperpigmentation spots, boosts collagen production, and restores radiant youthful glow.",
    vendorName: "Naija Glow Organic",
    vendorId: "vendor-6",
    isFeatured: false,
    stock: 50
  },
  {
    id: "beau-5",
    title: "Human Hair 24\" HD Lace Frontal Body Wave Wig",
    price: 115000,
    originalPrice: 135000,
    image: "https://images.unsplash.com/photo-1560869713-7d0a29430803?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    reviewsCount: 140,
    category: "beauty",
    description: "100% unprocessed virgin Brazilian human hair. Invisible HD lace melts seamlessly into all brown skin tones.",
    vendorName: "The Glam Factory NG",
    vendorId: "vendor-6",
    isFeatured: true,
    stock: 14
  },
  {
    id: "beau-6",
    title: "Gentleman's Organic Beard Oil & Balm Grooming Kit",
    price: 9800,
    originalPrice: 12500,
    image: "https://images.unsplash.com/photo-1621607512214-68297480165e?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    reviewsCount: 112,
    category: "beauty",
    description: "Jojoba, argan oil, and cedarwood blend that softens coarse beard hair, prevents itching, and stimulates healthy patch growth.",
    vendorName: "Royal Heritage Cosmetics",
    vendorId: "vendor-6",
    isFeatured: false,
    stock: 35
  },
  {
    id: "beau-7",
    title: "Broad Spectrum Sunscreen Gel SPF 50+ (100ml)",
    price: 7200,
    originalPrice: 9500,
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    reviewsCount: 210,
    category: "beauty",
    description: "Zero white-cast, lightweight non-greasy sunscreen gel formulated specifically for melanated skin under intense tropical sunlight.",
    vendorName: "Naija Glow Organic",
    vendorId: "vendor-6",
    isFeatured: true,
    stock: 60
  }
];

